Feature: test google features

  Scenario Outline: request, store and pick random person for google
    Given I request <amount> random people from API as "randomPeople"
    And I store "randomPeople" generated by API to our DB
    And I pick a random person FirstName and LastName from DB as "random_guy"
    Given I load google page
    Given I take value from "random_guy" and send it to google search
    When I perform search
    Then I see at a <search_results> search results for "random_guy"
    Examples:
      | amount | search_results |
      | 1      | 2              |
      | 2      | 3              |

  Scenario: request celebrity name
    Given "Ben Affleck" as "celebrity_1"
    Given I load google page
    Given I take value from "celebrity_1" and send it to google search
    When I perform search
    Then I see at a 4 search results for "celebrity_1"
